/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Billboard.glb --transform
Author: IronEqual (https://sketchfab.com/ie-niels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/billboard-from-poly-by-google-dc38fb47d0424cd0adde9f82616e8bf2
Title: Billboard from Poly by Google
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BillBoard(props) {
  const { nodes, materials } = useGLTF(
    "/models/billboard/Billboard-transformed.glb"
  );
  return (
    <group scale={0.023} {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.Tree_color}
      />
      <mesh geometry={nodes.Object_6.geometry} material={materials["Mat.3"]} />
    </group>
  );
}

useGLTF.preload("/models/billboard/Billboard-transformed.glb");
