/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 office_chair.glb --transform
Author: AK STUDIO (https://sketchfab.com/inven2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-chair-af2f07d06f6349158c1d24d87f5ceb95
Title: Office chair
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function OfficeChair(props) {
  const { nodes, materials } = useGLTF(
    "../public/models/chair/office_chair-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.53}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.Chair}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../public/models/chair/office_chair-transformed.glb");
